apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: var_nombreDeploymentConfig
spec:
  replicas: 1
  selector:
    app: var_nombreApp
    deploymentconfig: var_nombreDeploymentConfig
  template:
    metadata:
      labels:
        app: var_nombreApp
        deploymentconfig: var_nombreDeploymentConfig
    spec:
      containers:
      - resources:
            limits:
              memory: 320Mi
            requests:
              memory: 250Mi
        name: var_nombreApp
        readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        startupProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
        terminationMessagePolicy: File         
        image: var_nombreImagen
        ports:
        - containerPort: 8080